stages:
  - build
  - publish

default:
  image: node:22.9

variables:
  DOCKER_IMAGE: 1srael/coopera-rs-frontend
  DOCKER_TAG: latest

before_script:
  - rm -rf node_modules package-lock.json
  - npm install --legacy-peer-deps

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

publish:
  image: coopera-rs-frontend:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main  # ou o branch que você deseja publicar
